name: Deployment

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/cache-dependencies
  lint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use cached dependencies
        uses: ./.github/actions/cache-dependencies
      - uses: jitterbit/get-changed-files@v1
        id: get-changed-files
        continue-on-error: true
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint and annotate
        id: lint
        if: steps.get-changed-files.outputs.added_modified
        env:
          FILES: ${{ steps.get-changed-files.outputs.added_modified }}
        run: |
          FILTERED_FILES="$(echo $FILES | tr " " "\n" | grep -E "src/(.*)\.(ts|tsx)$" || true)"
          yarn lint-gh-action $FILTERED_FILES
  test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use cached dependencies
        uses: ./.github/actions/cache-dependencies
      - name: Test
        run: yarn test:coverage
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl -X POST ${{ secrets.DEPLOYMENT_WEB_HOOK_URL }}
